from django.core.management.base import BaseCommand
from AgentMap.models import HouseHoldDiscount, State, Carrier, HouseHoldDiscountKey
import time


def add_color_mapping_to_model():
    colorMapping = {
        "Alabama": {
            "AARP": "SPOUSAL",
            "American Benefit Life": "RM",
            "Ace Chubb": "RM",
            "Aetna": "SPOUSAL",
            "Aflac": "RM",
            "American Financial Security": "SPOUSAL",
            "American Home Life": "SPOUSAL",
            "Cigna National Health Insurance": "RM",
            "Elips Life Insurance": "NONE",
            "LifeShield National Insurance": "RM",
            "Manhattan Life": "RM",
            "Med Mutual Protect": "RM",
            "Mutual of Omaha": "RM",
            "United American": "NONE",
            "Atlantic Capital Life Assurance (BFAM)": "SPOUSAL",
            "Bankers Fidelity Assurance (BFAM)": "SPOUSAL",
            "Bankers Fidelity Insurance (BFAM)": "SPOUSAL",
        },
        "Alaska": {
            "AARP": "SPOUSAL",
            "Ace Chubb": "RM",
            "Aetna": "SPOUSAL",
            "Aflac": "RM",
            "Cigna Loyal American Life Insurance": "SPOUSAL",
            "Mutual of Omaha": "NONE",
            "United American": "NONE",
            "Atlantic Capital Life Assurance (BFAM)": "SPOUSAL",
            "Bankers Fidelity Assurance (BFAM)": "SPOUSAL",
            "Bankers Fidelity Insurance (BFAM)": "SPOUSAL",
        },
        "Arizona": {
            "AARP": "SPOUSAL",
            "AARP UHICA": "RM",
            "American Benefit Life": "RM",
            "Ace Chubb": "RM",
            "Aetna": "SPOUSAL",
            "Aflac": "RM",
            "American Financial Security": "SPOUSAL",
            "American Home Life": "SPOUSAL",
            "Cigna National Health Insurance": "RM",
            "Elips Life Insurance": "RM",
            "LifeShield National Insurance": "RM",
            "New Era": "SPOUSAL",
            "Manhattan Life": "RM",
            "Med Mutual Protect": "RM",
            "Medico": "RM",
            "Mutual of Omaha": "RM",
            "WPS Health Insurance": "SPOUSAL",
            "United American": "NONE",
            "Atlantic Capital Life Assurance (BFAM)": "SPOUSAL",
            "Bankers Fidelity Assurance (BFAM)": "SPOUSAL",
            "Bankers Fidelity Insurance (BFAM)": "SPOUSAL",
        },
        "Arkansas": {
            "AARP": "SPOUSAL",
            "AARP UHICA": "RM",
            "American Benefit Life": "RM",
            "Ace Chubb": "RM",
            "Aetna": "SPOUSAL",
            "Aflac": "RM",
            "American Home Life": "SPOUSAL",
            "Cigna Health and Life Insurance": "RM",
            "Elips Life Insurance": "RM",
            "LifeShield National Insurance": "RM",
            "Manhattan Life": "RM",
            "Med Mutual Protect": "RM",
            "Mutual of Omaha": "RM",
            "WPS Health Insurance": "SPOUSAL",
            "United American": "NONE",
            "Atlantic Capital Life Assurance (BFAM)": "SPOUSAL",
            "Bankers Fidelity Assurance (BFAM)": "SPOUSAL",
            "Bankers Fidelity Insurance (BFAM)": "SPOUSAL",
        },
        "California": {
            "AARP": "SPOUSAL",
            "Aetna": "SPOUSAL",
            "Aflac": "RM",
            "Cigna Health and Life Insurance": "RM",
            "Elips Life Insurance": "RM",
            "Manhattan Life": "RM",
            "Mutual of Omaha": "RM",
            "United American": "NONE",
            "Atlantic Capital Life Assurance (BFAM)": "SPOUSAL",
            "Bankers Fidelity Assurance (BFAM)": "SPOUSAL",
            "Bankers Fidelity Insurance (BFAM)": "SPOUSAL",
        },
        "Colorado": {
            "AARP": "SPOUSAL",
            "Ace Chubb": "RM",
            "Aetna": "SPOUSAL",
            "Aflac": "RM",
            "American Home Life": "SPOUSAL",
            "Cigna National Health Insurance": "RM",
            "LifeShield National Insurance": "RM",
            "Lumico": "RM",
            "Manhattan Life": "RM",
            "Med Mutual Protect": "RM",
            "Medico": "RM",
            "Mutual of Omaha": "RM",
            "WPS Health Insurance": "SPOUSAL",
            "United American": "NONE",
            "Atlantic Capital Life Assurance (BFAM)": "SPOUSAL",
            "Bankers Fidelity Assurance (BFAM)": "SPOUSAL",
            "Bankers Fidelity Insurance (BFAM)": "SPOUSAL",
        },
        "Connecticut": {
            "AARP": "SPOUSAL",
            "American Benefit Life": "RM",
            "Aetna": "NONE",
            "Cigna National Health Insurance": "SPOUSAL",
            "Mutual of Omaha": "NONE",
            "United American": "NONE",
            "Atlantic Capital Life Assurance (BFAM)": "SPOUSAL",
            "Bankers Fidelity Assurance (BFAM)": "SPOUSAL",
            "Bankers Fidelity Insurance (BFAM)": "SPOUSAL",
        },
        "Delaware": {
            "AARP": "SPOUSAL",
            "American Benefit Life": "RM",
            "Aetna": "SPOUSAL",
            "Aflac": "RM",
            "American Financial Security": "SPOUSAL",
            "Cigna Health and Life Insurance": "RM",
            "Elips Life Insurance": "RM",
            "LifeShield National Insurance": "RM",
            "Mutual of Omaha": "RM",
            "WPS Health Insurance": "SPOUSAL",
            "United American": "NONE",
            "Atlantic Capital Life Assurance (BFAM)": "SPOUSAL",
            "Bankers Fidelity Assurance (BFAM)": "SPOUSAL",
            "Bankers Fidelity Insurance (BFAM)": "SPOUSAL",
        },
        "District of Columbia": {
            "Aetna": "SPOUSAL",
            "Cigna Loyal American Life Insurance": "SPOUSAL",
            "LifeShield National Insurance": "RM",
            "Mutual of Omaha": "NONE",
            "Atlantic Capital Life Assurance (BFAM)": "SPOUSAL",
            "Bankers Fidelity Assurance (BFAM)": "SPOUSAL",
            "Bankers Fidelity Insurance (BFAM)": "SPOUSAL",
        },
        "Florida": {
            "AARP": "SPOUSAL",
            "American Benefit Life": "SPOUSAL",
            "Ace Chubb": "SPOUSAL",
            "Aetna": "NONE",
            "Aflac": "SPOUSAL",
            "American Home Life": "SPOUSAL",
            "Cigna Health and Life Insurance": "SPOUSAL",
            "LifeShield National Insurance": "SPOUSAL",
            "New Era": "NONE",
            "Med Mutual Protect": "RM",
            "Mutual of Omaha": "NONE",
            "WPS Health Insurance": "SPOUSAL",
            "United American": "NONE",
            "Atlantic Capital Life Assurance (BFAM)": "SPOUSAL",
            "Bankers Fidelity Assurance (BFAM)": "SPOUSAL",
            "Bankers Fidelity Insurance (BFAM)": "SPOUSAL",
        },
        "Georgia": {
            "AARP": "SPOUSAL",
            "American Benefit Life": "RM",
            "Ace Chubb": "RM",
            "Aetna": "SPOUSAL",
            "Aflac": "RM",
            "American Financial Security": "SPOUSAL",
            "American Home Life": "SPOUSAL",
            "Cigna National Health Insurance": "RM",
            "Elips Life Insurance": "RM",
            "LifeShield National Insurance": "RM",
            "Manhattan Life": "RM",
            "Medico": "RM",
            "Med Mutual Protect": "RM",
            "Mutual of Omaha": "RM",
            "United American": "NONE",
            "Atlantic Capital Life Assurance (BFAM)": "SPOUSAL",
            "Bankers Fidelity Assurance (BFAM)": "SPOUSAL",
            "Bankers Fidelity Insurance (BFAM)": "SPOUSAL",
        },
        "Hawaii": {
            "Cigna Loyal American Life Insurance": "NONE",
            "Mutual of Omaha": "NONE",
            "United American": "NONE",
            "Atlantic Capital Life Assurance (BFAM)": "SPOUSAL",
            "Bankers Fidelity Assurance (BFAM)": "SPOUSAL",
            "Bankers Fidelity Insurance (BFAM)": "SPOUSAL",
        },
        "Idaho": {
            "AARP": "SPOUSAL",
            "Ace Chubb": "NONE",
            "Aetna": "NONE",
            "Aflac": "NONE",
            "Cigna Health and Life Insurance": "NONE",
            "Manhattan Life": "NONE",
            "Mutual of Omaha": "NONE",
            "United American": "NONE",
            "Atlantic Capital Life Assurance (BFAM)": "SPOUSAL",
            "Bankers Fidelity Assurance (BFAM)": "SPOUSAL",
            "Bankers Fidelity Insurance (BFAM)": "SPOUSAL",
        },
        "Illinois": {
            "AARP": "SPOUSAL",
            "AARP UHICA": "RM",
            "American Benefit Life": "RM",
            "Ace Chubb": "RM",
            "Aetna": "SPOUSAL",
            "Aflac": "RM",
            "American Financial Security": "SPOUSAL",
            "American Home Life": "RM",
            "Cigna National Health Insurance": "RM",
            "LifeShield National Insurance": "RM",
            "Manhattan Life": "RM",
            "Medico": "RM",
            "Med Mutual Protect": "RM",
            "Mutual of Omaha": "RM",
            "WPS Health Insurance": "SPOUSAL",
            "United American": "NONE",
            "Atlantic Capital Life Assurance (BFAM)": "SPOUSAL",
            "Bankers Fidelity Assurance (BFAM)": "SPOUSAL",
            "Bankers Fidelity Insurance (BFAM)": "SPOUSAL",
        },
        "Iowa": {
            "AARP": "SPOUSAL",
            "American Benefit Life": "RM",
            "Ace Chubb": "RM",
            "Aetna": "SPOUSAL",
            "Aflac": "RM",
            "American Home Life": "SPOUSAL",
            "Cigna Health and Life Insurance": "SPOUSAL",
            "LifeShield National Insurance": "RM",
            "Manhattan Life": "RM",
            "Medico": "RM",
            "Med Mutual Protect": "RM",
            "Mutual of Omaha": "RM",
            "WPS Health Insurance": "SPOUSAL",
            "United American": "NONE",
            "Atlantic Capital Life Assurance (BFAM)": "SPOUSAL",
            "Bankers Fidelity Assurance (BFAM)": "SPOUSAL",
            "Bankers Fidelity Insurance (BFAM)": "SPOUSAL",
        },
        "Indiana": {
            "AARP": "SPOUSAL",
            "AARP UHICA": "RM",
            "American Benefit Life": "SPOUSAL",
            "Ace Chubb": "SPOUSAL",
            "Aetna": "SPOUSAL",
            "Aflac": "RM",
            "American Home Life": "SPOUSAL",
            "American Financial Security": "SPOUSAL",
            "Cigna National Health Insurance": "RM",
            "Elips Life Insurance": "SPOUSAL",
            "LifeShield National Insurance": "RM",
            "New Era": "SPOUSAL",
            "Manhattan Life": "RM",
            "Med Mutual Protect": "RM",
            "Medico": "RM",
            "Mutual of Omaha": "RM",
            "WPS Health Insurance": "SPOUSAL",
            "United American": "NONE",
            "Atlantic Capital Life Assurance (BFAM)": "SPOUSAL",
            "Bankers Fidelity Assurance (BFAM)": "SPOUSAL",
            "Bankers Fidelity Insurance (BFAM)": "SPOUSAL",
        },
        "Kansas": {
            "AARP": "SPOUSAL",
            "AARP UHICA": "RM",
            "American Benefit Life": "RM",
            "Ace Chubb": "RM",
            "Aetna": "SPOUSAL",
            "Aflac": "RM",
            "American Home Life": "SPOUSAL",
            "Cigna National Health Insurance": "RM",
            "Elips Life Insurance": "RM",
            "LifeShield National Insurance": "RM",
            "Manhattan Life": "RM",
            "Medico": "RM",
            "Med Mutual Protect": "RM",
            "Mutual of Omaha": "RM",
            "WPS Health Insurance": "SPOUSAL",
            "United American": "NONE",
            "Atlantic Capital Life Assurance (BFAM)": "SPOUSAL",
            "Bankers Fidelity Assurance (BFAM)": "SPOUSAL",
            "Bankers Fidelity Insurance (BFAM)": "SPOUSAL",
        },
        "Kentucky": {
            "AARP": "SPOUSAL",
            "American Benefit Life": "SPOUSAL",
            "Ace Chubb": "RM",
            "Aetna": "SPOUSAL",
            "Aflac": "SPOUSAL",
            "American Financial Security": "SPOUSAL",
            "Cigna National Health Insurance": "RM",
            "Elips Life Insurance": "RM",
            "LifeShield National Insurance": "RM",
            "Manhattan Life": "RM",
            "Medico": "RM",
            "Med Mutual Protect": "RM",
            "Mutual of Omaha": "RM",
            "WPS Health Insurance": "SPOUSAL",
            "United American": "NONE",
            "Atlantic Capital Life Assurance (BFAM)": "SPOUSAL",
            "Bankers Fidelity Assurance (BFAM)": "SPOUSAL",
            "Bankers Fidelity Insurance (BFAM)": "SPOUSAL",
        },
        "Louisiana": {
            "AARP": "SPOUSAL",
            "American Benefit Life": "RM",
            "Ace Chubb": "RM",
            "Aetna": "SPOUSAL",
            "Aflac": "RM",
            "American Home Life": "SPOUSAL",
            "Cigna National Health Insurance": "RM",
            "Elips Life Insurance": "RM",
            "LifeShield National Insurance": "RM",
            "Manhattan Life": "RM",
            "Medico": "RM",
            "Med Mutual Protect": "RM",
            "Mutual of Omaha": "RM",
            "Philadelphia American Life Insurance": "SPOUSAL",
            "United American": "NONE",
            "Atlantic Capital Life Assurance (BFAM)": "SPOUSAL",
            "Bankers Fidelity Assurance (BFAM)": "SPOUSAL",
            "Bankers Fidelity Insurance (BFAM)": "SPOUSAL",
        },
        "Maine": {
            "AARP": "SPOUSAL",
            "Cigna Health and Life Insurance": "SPOUSAL",
            "Mutual of Omaha": "SPOUSAL",
            "United American": "NONE",
            "Atlantic Capital Life Assurance (BFAM)": "SPOUSAL",
            "Bankers Fidelity Assurance (BFAM)": "SPOUSAL",
            "Bankers Fidelity Insurance (BFAM)": "SPOUSAL",
        },
        "Maryland": {
            "AARP": "SPOUSAL",
            "American Benefit Life": "RM",
            "Ace Chubb": "RM",
            "Aetna": "SPOUSAL",
            "Aflac": "RM",
            "American Financial Security": "SPOUSAL",
            "American Home Life": "SPOUSAL",
            "Cigna National Health Insurance": "RM",
            "LifeShield National Insurance": "RM",
            "Manhattan Life": "RM",
            "Mutual of Omaha": "RM",
            "WPS Health Insurance": "SPOUSAL",
            "United American": "NONE",
            "Atlantic Capital Life Assurance (BFAM)": "SPOUSAL",
            "Bankers Fidelity Assurance (BFAM)": "SPOUSAL",
            "Bankers Fidelity Insurance (BFAM)": "SPOUSAL",
        },
        "Massachusetts": {
        },
        "Michigan": {
            "AARP": "SPOUSAL",
            "American Benefit Life": "RM",
            "Ace Chubb": "RM",
            "Aetna": "SPOUSAL",
            "Aflac": "RM",
            "American Home Life": "SPOUSAL",
            "Cigna National Health Insurance": "RM",
            "Elips Life Insurance": "RM",
            "Manhattan Life": "RM",
            "Medico": "RM",
            "Med Mutual Protect": "RM",
            "Mutual of Omaha": "RM",
            "Philadelphia American Life Insurance": "SPOUSAL",
            "WPS Health Insurance": "SPOUSAL",
            "United American": "NONE",
            "Atlantic Capital Life Assurance (BFAM)": "SPOUSAL",
            "Bankers Fidelity Assurance (BFAM)": "SPOUSAL",
            "Bankers Fidelity Insurance (BFAM)": "SPOUSAL",
        },
        "Minnesota": {
            "AARP": "SPOUSAL",
            "Aetna": "NONE",
            "Cigna Health and Life Insurance": "NONE",
            "Lumico": "NONE",
            "Mutual of Omaha": "NONE",
            "United American": "NONE",
            "Atlantic Capital Life Assurance (BFAM)": "SPOUSAL",
            "Bankers Fidelity Assurance (BFAM)": "SPOUSAL",
            "Bankers Fidelity Insurance (BFAM)": "SPOUSAL",
        },
        "Mississippi": {
            "AARP": "SPOUSAL",
            "AARP UHICA": "RM",
            "American Benefit Life": "RM",
            "Ace Chubb": "RM",
            "Aetna": "SPOUSAL",
            "Aflac": "RM",
            "American Financial Security": "SPOUSAL",
            "American Home Life": "SPOUSAL",
            "Cigna Health and Life Insurance": "SPOUSAL",
            "Cigna National Health Insurance": "RM",
            "Elips Life Insurance": "RM",
            "LifeShield National Insurance": "RM",
            "Manhattan Life": "RM",
            "Medico": "RM",
            "Med Mutual Protect": "RM",
            "Mutual of Omaha": "RM",
            "United American": "NONE",
            "Atlantic Capital Life Assurance (BFAM)": "SPOUSAL",
            "Bankers Fidelity Assurance (BFAM)": "SPOUSAL",
            "Bankers Fidelity Insurance (BFAM)": "SPOUSAL",
        },
        "Missouri": {
            "AARP": "SPOUSAL",
            "AARP UHICA": "RM",
            "Ace Chubb": "RM",
            "Aetna": "SPOUSAL",
            "Aflac": "RM",
            "American Home Life": "SPOUSAL",
            "Cigna National Health Insurance": "RM",
            "Cigna Health and Life Insurance": "SPOUSAL",
            "LifeShield National Insurance": "RM",
            "Manhattan Life": "RM",
            "Medico": "RM",
            "Med Mutual Protect": "RM",
            "Mutual of Omaha": "MARRIED",
            "WPS Health Insurance": "SPOUSAL",
            "United American": "NONE",
            "Atlantic Capital Life Assurance (BFAM)": "SPOUSAL",
            "Bankers Fidelity Assurance (BFAM)": "SPOUSAL",
            "Bankers Fidelity Insurance (BFAM)": "SPOUSAL",
        },
        "Montana": {
            "AARP": "SPOUSAL",
            "Ace Chubb": "RM",
            "Aetna": "SPOUSAL",
            "Aflac": "RM",
            "American Financial Security": "SPOUSAL",
            "American Home Life": "SPOUSAL",
            "Cigna Health and Life Insurance": "RM",
            "Lumico": "RM",
            "Mutual of Omaha": "RM",
            "WPS Health Insurance": "SPOUSAL",
            "United American": "NONE",
            "Atlantic Capital Life Assurance (BFAM)": "SPOUSAL",
            "Bankers Fidelity Assurance (BFAM)": "SPOUSAL",
            "Bankers Fidelity Insurance (BFAM)": "SPOUSAL",
        },
        "Nebraska": {
            "AARP": "SPOUSAL",
            "American Benefit Life": "RM",
            "Ace Chubb": "RM",
            "Aetna": "SPOUSAL",
            "Aflac": "RM",
            "American Financial Security": "SPOUSAL",
            "American Home Life": "SPOUSAL",
            "Cigna Health and Life Insurance": "RM",
            "LifeShield National Insurance": "RM",
            "Manhattan Life": "RM",
            "Medico": "RM",
            "Med Mutual Protect": "RM",
            "Mutual of Omaha": "RM",
            "WPS Health Insurance": "SPOUSAL",
            "United American": "NONE",
            "Atlantic Capital Life Assurance (BFAM)": "SPOUSAL",
            "Bankers Fidelity Assurance (BFAM)": "SPOUSAL",
            "Bankers Fidelity Insurance (BFAM)": "SPOUSAL",
        },
        "Nevada": {
            "AARP": "RM",
            "American Benefit Life": "RM",
            "Ace Chubb": "RM",
            "Aetna": "SPOUSAL",
            "Aflac": "RM",
            "American Financial Security": "SPOUSAL",
            "American Home Life": "SPOUSAL",
            "Cigna National Health Insurance": "RM",
            "LifeShield National Insurance": "RM",
            "Manhattan Life": "RM",
            "Mutual of Omaha": "RM",
            "Med Mutual Protect": "RM",
            "WPS Health Insurance": "SPOUSAL",
            "Atlantic Capital Life Assurance (BFAM)": "SPOUSAL",
            "Bankers Fidelity Assurance (BFAM)": "SPOUSAL",
            "Bankers Fidelity Insurance (BFAM)": "SPOUSAL",
        },
        "New Hampshire": {
            "AARP": "SPOUSAL",
            "Ace Chubb": "RM",
            "Aetna": "SPOUSAL",
            "Aflac": "RM",
            "Cigna Health and Life Insurance": "RM",
            "Mutual of Omaha": "RM",
            "United American": "NONE",
            "Atlantic Capital Life Assurance (BFAM)": "SPOUSAL",
            "Bankers Fidelity Assurance (BFAM)": "SPOUSAL",
            "Bankers Fidelity Insurance (BFAM)": "SPOUSAL",
        },
        "New Jersey": {
            "AARP": "SPOUSAL",
            "AARP UHICA": "RM",
            "American Benefit Life": "SPOUSAL",
            "Ace Chubb": "SPOUSAL",
            "Aetna": "SPOUSAL",
            "Aflac": "SPOUSAL",
            "Cigna Health and Life Insurance": "SPOUSAL",
            "Cigna National Health Insurance": "RM",
            "Lumico": "SPOUSAL",
            "LifeShield National Insurance": "SPOUSAL",
            "Manhattan Life": "SPOUSAL",
            "Mutual of Omaha": "SPOUSAL",
            "United American": "NONE",
            "Atlantic Capital Life Assurance (BFAM)": "SPOUSAL",
            "Bankers Fidelity Assurance (BFAM)": "SPOUSAL",
            "Bankers Fidelity Insurance (BFAM)": "SPOUSAL",
        },
        "New Mexico": {
            "AARP": "SPOUSAL",
            "American Benefit Life": "RM",
            "Ace Chubb": "RM",
            "Aetna": "SPOUSAL",
            "Aflac": "RM",
            "American Financial Security": "SPOUSAL",
            "American Home Life": "SPOUSAL",
            "Cigna Health and Life Insurance": "RM",
            "LifeShield National Insurance": "RM",
            "Lumico": "RM",
            "Manhattan Life": "RM",
            "Mutual of Omaha": "RM",
            "Med Mutual Protect": "RM",
            "United American": "NONE",
            "Atlantic Capital Life Assurance (BFAM)": "SPOUSAL",
            "Bankers Fidelity Assurance (BFAM)": "SPOUSAL",
            "Bankers Fidelity Insurance (BFAM)": "SPOUSAL",
        },
        "New York": {
            "AARP": "NONE",
            "Mutual of Omaha": "NONE",
            "Atlantic Capital Life Assurance (BFAM)": "SPOUSAL",
            "Bankers Fidelity Assurance (BFAM)": "SPOUSAL",
            "Bankers Fidelity Insurance (BFAM)": "SPOUSAL",
        },
        "North Carolina": {
            "AARP": "SPOUSAL",
            "AARP UHICA": "RM",
            "American Benefit Life": "RM",
            "Ace Chubb": "RM",
            "Aetna": "SPOUSAL",
            "Aflac": "RM",
            "American Financial Security": "SPOUSAL",
            "American Home Life": "SPOUSAL",
            "Cigna National Health Insurance": "RM",
            "Elips Life Insurance": "RM",
            "LifeShield National Insurance": "RM",
            "Manhattan Life": "RM",
            "Medico": "RM",
            "Mutual of Omaha": "RM",
            "United American": "NONE",
            "Atlantic Capital Life Assurance (BFAM)": "SPOUSAL",
            "Bankers Fidelity Assurance (BFAM)": "SPOUSAL",
            "Bankers Fidelity Insurance (BFAM)": "SPOUSAL",
        },
        "North Dakota": {
            "AARP UHICA": "RM",
            "American Benefit Life": "RM",
            "Ace Chubb": "SPOUSAL",
            "Aetna": "NONE",
            "Aflac": "SPOUSAL",
            "American Financial Security": "SPOUSAL",
            "American Home Life": "SPOUSAL",
            "Cigna Health and Life Insurance": "RM",
            "Elips Life Insurance": "SPOUSAL",
            "LifeShield National Insurance": "SPOUSAL",
            "Manhattan Life": "SPOUSAL",
            "Mutual of Omaha": "RM",
            "WPS Health Insurance": "SPOUSAL",
            "United American": "NONE",
            "Atlantic Capital Life Assurance (BFAM)": "SPOUSAL",
            "Bankers Fidelity Assurance (BFAM)": "SPOUSAL",
            "Bankers Fidelity Insurance (BFAM)": "SPOUSAL",
        },
        "Ohio": {
            "AARP": "SPOUSAL",
            "AARP UHICA": "RM",
            "American Benefit Life": "SPOUSAL",
            "Ace Chubb": "SPOUSAL",
            "Aetna": "SPOUSAL",
            "Aflac": "SPOUSAL",
            "American Financial Security": "SPOUSAL",
            "American Home Life": "SPOUSAL",
            "Cigna National Health Insurance": "SPOUSAL",
            "Elips Life Insurance": "SPOUSAL",
            "LifeShield National Insurance": "SPOUSAL",
            "Manhattan Life": "SPOUSAL",
            "Medico": "SPOUSAL",
            "Mutual of Omaha": "SPOUSAL",
            "WPS Health Insurance": "SPOUSAL",
            "United American": "NONE",
            "Atlantic Capital Life Assurance (BFAM)": "SPOUSAL",
            "Bankers Fidelity Assurance (BFAM)": "SPOUSAL",
            "Bankers Fidelity Insurance (BFAM)": "SPOUSAL",
        },
        "Oklahoma": {
            "AARP": "SPOUSAL",
            "AARP UHICA": "RM",
            "American Benefit Life": "SPOUSAL",
            "Ace Chubb": "SPOUSAL",
            "Aetna": "SPOUSAL",
            "Aflac": "SPOUSAL",
            "American Financial Security": "SPOUSAL",
            "American Home Life": "SPOUSAL",
            "Cigna National Health Insurance": "SPOUSAL",
            "LifeShield National Insurance": "SPOUSAL",
            "New Era": "SPOUSAL",
            "Manhattan Life": "SPOUSAL",
            "Med Mutual Protect": "RM",
            "Medico": "SPOUSAL",
            "Mutual of Omaha": "SPOUSAL",
            "WPS Health Insurance": "SPOUSAL",
            "United American": "NONE",
            "Atlantic Capital Life Assurance (BFAM)": "SPOUSAL",
            "Bankers Fidelity Assurance (BFAM)": "SPOUSAL",
            "Bankers Fidelity Insurance (BFAM)": "SPOUSAL",
        },
        "Oregon": {
            "AARP": "SPOUSAL",
            "Aetna": "RM",
            "Aflac": "RM",
            "Cigna Health and Life Insurance": "RM",
            "LifeShield National Insurance": "RM",
            "Lumico": "RM",
            "Manhattan Life": "RM",
            "Mutual of Omaha": "RM",
            "United American": "NONE",
            "Atlantic Capital Life Assurance (BFAM)": "SPOUSAL",
            "Bankers Fidelity Assurance (BFAM)": "SPOUSAL",
            "Bankers Fidelity Insurance (BFAM)": "SPOUSAL",
        },
        "Pennsylvania": {
            "AARP": "SPOUSAL",
            "AARP UHICA": "RM",
            "American Benefit Life": "RM",
            "Ace Chubb": "SPOUSAL",
            "Aetna": "SPOUSAL",
            "Aflac": "RM",
            "American Financial Security": "SPOUSAL",
            "Cigna National Health Insurance": "MARRIED",
            "Elips Life Insurance": "RM",
            "LifeShield National Insurance": "RM",
            "Manhattan Life": "SPOUSAL",
            "Medico": "MARRIED",
            "Med Mutual Protect": "RM",
            "Mutual of Omaha": "MARRIED",
            "WPS Health Insurance": "SPOUSAL",
            "United American": "NONE",
            "Atlantic Capital Life Assurance (BFAM)": "SPOUSAL",
            "Bankers Fidelity Assurance (BFAM)": "SPOUSAL",
            "Bankers Fidelity Insurance (BFAM)": "SPOUSAL",
        },
        "Rhode Island": {
            "AARP": "SPOUSAL",
            "Ace Chubb": "RM",
            "Aetna": "SPOUSAL",
            "Aflac": "RM",
            "Cigna Health and Life Insurance": "RM",
            "Mutual of Omaha": "RM",
            "United American": "NONE",
            "Atlantic Capital Life Assurance (BFAM)": "SPOUSAL",
            "Bankers Fidelity Assurance (BFAM)": "SPOUSAL",
            "Bankers Fidelity Insurance (BFAM)": "SPOUSAL",
        },
        "South Carolina": {
            "AARP": "SPOUSAL",
            "AARP UHICA": "RM",
            "American Benefit Life": "RM",
            "Ace Chubb": "RM",
            "Aetna": "SPOUSAL",
            "Aflac": "RM",
            "American Home Life": "SPOUSAL",
            "Cigna National Health Insurance": "RM",
            "Elips Life Insurance": "RM",
            "LifeShield National Insurance": "RM",
            "Manhattan Life": "RM",
            "Medico": "RM",
            "Med Mutual Protect": "RM",
            "Mutual of Omaha": "RM",
            "Philadelphia American Life Insurance": "SPOUSAL",
            "United American": "NONE",
            "Atlantic Capital Life Assurance (BFAM)": "SPOUSAL",
            "Bankers Fidelity Assurance (BFAM)": "SPOUSAL",
            "Bankers Fidelity Insurance (BFAM)": "SPOUSAL",
        },
        "South Dakota": {
            "AARP": "SPOUSAL",
            "American Benefit Life": "RM",
            "Ace Chubb": "RM",
            "Aetna": "NONE",
            "Aflac": "RM",
            "American Financial Security": "SPOUSAL",
            "American Home Life": "SPOUSAL",
            "Cigna National Health Insurance": "RM",
            "LifeShield National Insurance": "RM",
            "Manhattan Life": "RM",
            "Med Mutual Protect": "RM",
            "Mutual of Omaha": "RM",
            "Philadelphia American Life Insurance": "SPOUSAL",
            "WPS Health Insurance": "SPOUSAL",
            "United American": "NONE",
            "Atlantic Capital Life Assurance (BFAM)": "SPOUSAL",
            "Bankers Fidelity Assurance (BFAM)": "SPOUSAL",
            "Bankers Fidelity Insurance (BFAM)": "SPOUSAL",
        },
        "Tennessee": {
            "AARP": "SPOUSAL",
            "AARP UHICA": "RM",
            "American Benefit Life": "RM",
            "Ace Chubb": "RM",
            "Aetna": "SPOUSAL",
            "Aflac": "RM",
            "American Home Life": "SPOUSAL",
            "Cigna National Health Insurance": "RM",
            "Elips Life Insurance": "RM",
            "LifeShield National Insurance": "RM",
            "New Era": "NONE",
            "Manhattan Life": "RM",
            "Med Mutual Protect": "RM",
            "Medico": "RM",
            "Mutual of Omaha": "RM",
            "WPS Health Insurance": "SPOUSAL",
            "United American": "NONE",
            "Atlantic Capital Life Assurance (BFAM)": "SPOUSAL",
            "Bankers Fidelity Assurance (BFAM)": "SPOUSAL",
            "Bankers Fidelity Insurance (BFAM)": "SPOUSAL",
        },
        "Texas": {
            "AARP": "SPOUSAL",
            "AARP UHICA": "RM",
            "American Benefit Life": "RM",
            "Ace Chubb": "RM",
            "Aetna": "SPOUSAL",
            "Aflac": "RM",
            "American Financial Security": "SPOUSAL",
            "American Home Life": "SPOUSAL",
            "Cigna National Health Insurance": "RM",
            "Elips Life Insurance": "RM",
            "LifeShield National Insurance": "RM",
            "Manhattan Life": "RM",
            "Med Mutual Protect": "RM",
            "Medico": "RM",
            "Mutual of Omaha": "RM",
            "Philadelphia American Life Insurance": "SPOUSAL",
            "WPS Health Insurance": "SPOUSAL",
            "United American": "NONE",
            "Atlantic Capital Life Assurance (BFAM)": "SPOUSAL",
            "Bankers Fidelity Assurance (BFAM)": "SPOUSAL",
            "Bankers Fidelity Insurance (BFAM)": "SPOUSAL",
        },
        "Utah": {
            "AARP": "SPOUSAL",
            "American Benefit Life": "RM",
            "Ace Chubb": "RM",
            "Aetna": "SPOUSAL",
            "American Financial Security": "SPOUSAL",
            "American Home Life": "SPOUSAL",
            "Cigna National Health Insurance": "RM",
            "Elips Life Insurance": "RM",
            "LifeShield National Insurance": "RM",
            "Medico": "RM",
            "Mutual of Omaha": "RM",
            "Med Mutual Protect": "RM",
            "United American": "NONE",
            "Atlantic Capital Life Assurance (BFAM)": "SPOUSAL",
            "Bankers Fidelity Assurance (BFAM)": "SPOUSAL",
            "Bankers Fidelity Insurance (BFAM)": "SPOUSAL",
        },
        "Vermont": {
            "AARP": "NONE",
            "Aetna": "NONE",
            "Aflac": "NONE",
            "Cigna Health and Life Insurance": "NONE",
            "Mutual of Omaha": "NONE",
            "WPS Health Insurance": "SPOUSAL",
            "United American": "NONE",
            "Atlantic Capital Life Assurance (BFAM)": "SPOUSAL",
            "Bankers Fidelity Assurance (BFAM)": "SPOUSAL",
            "Bankers Fidelity Insurance (BFAM)": "SPOUSAL",
        },
        "Virginia": {
            "AARP": "SPOUSAL",
            "American Benefit Life": "RM",
            "Ace Chubb": "RM",
            "Aetna": "SPOUSAL",
            "Aflac": "RM",
            "American Financial Security": "SPOUSAL",
            "American Home Life": "SPOUSAL",
            "Cigna Health and Life Insurance": "SPOUSAL",
            "Elips Life Insurance": "RM",
            "LifeShield National Insurance": "RM",
            "Manhattan Life": "RM",
            "Medico": "RM",
            "Mutual of Omaha": "RM",
            "Med Mutual Protect": "RM",
            "United American": "NONE",
            "Atlantic Capital Life Assurance (BFAM)": "SPOUSAL",
            "Bankers Fidelity Assurance (BFAM)": "SPOUSAL",
            "Bankers Fidelity Insurance (BFAM)": "SPOUSAL",
        },
        "Washington": {
            "AARP": "SPOUSAL",
            "Cigna Health and Life Insurance": "SPOUSAL",
            "Elips Life Insurance": "SPOUSAL",
            "Medico": "SPOUSAL",
            "Mutual of Omaha": "SPOUSAL",
            "United American": "NONE",
            "Atlantic Capital Life Assurance (BFAM)": "SPOUSAL",
            "Bankers Fidelity Assurance (BFAM)": "SPOUSAL",
            "Bankers Fidelity Insurance (BFAM)": "SPOUSAL",
        },
        "West Virginia": {
            "AARP": "SPOUSAL",
            "American Benefit Life": "RM",
            "Ace Chubb": "RM",
            "Aetna": "SPOUSAL",
            "Aflac": "RM",
            "American Home Life": "SPOUSAL",
            "Cigna Health and Life Insurance": "RM",
            "LifeShield National Insurance": "RM",
            "Manhattan Life": "RM",
            "Medico": "RM",
            "Med Mutual Protect": "RM",
            "Mutual of Omaha": "RM",
            "WPS Health Insurance": "SPOUSAL",
            "United American": "NONE",
            "Atlantic Capital Life Assurance (BFAM)": "SPOUSAL",
            "Bankers Fidelity Assurance (BFAM)": "SPOUSAL",
            "Bankers Fidelity Insurance (BFAM)": "SPOUSAL",
        },
        "Wisconsin": {
            "AARP": "SPOUSAL",
            "American Benefit Life": "RM",
            "Ace Chubb": "RM",
            "Aetna": "SPOUSAL",
            "Aflac": "RM",
            "American Home Life": "SPOUSAL",
            "Cigna National Health Insurance": "RM",
            "Elips Life Insurance": "RM",
            "Manhattan Life": "RM",
            "Medico": "RM",
            "Med Mutual Protect": "RM",
            "Mutual of Omaha": "RM",
            "WPS Health Insurance": "SPOUSAL",
            "United American": "NONE",
            "Atlantic Capital Life Assurance (BFAM)": "SPOUSAL",
            "Bankers Fidelity Assurance (BFAM)": "SPOUSAL",
            "Bankers Fidelity Insurance (BFAM)": "SPOUSAL",
        },
        "Wyoming": {
            "AARP": "SPOUSAL",
            "Ace Chubb": "RM",
            "Aetna": "SPOUSAL",
            "Aflac": "RM",
            "American Home Life": "SPOUSAL",
            "Cigna Health and Life Insurance": "RM",
            "LifeShield National Insurance": "RM",
            "Manhattan Life": "RM",
            "Mutual of Omaha": "RM",
            "Med Mutual Protect": "RM",
            "United American": "NONE",
            "Atlantic Capital Life Assurance (BFAM)": "SPOUSAL",
            "Bankers Fidelity Assurance (BFAM)": "SPOUSAL",
            "Bankers Fidelity Insurance (BFAM)": "SPOUSAL",
        }
    }

    ColorKey = {
        "SPOUSAL": "oklch(78.19% 0.072 202.61)",
        "NONE": "oklch(76.85% 0.086 33.54)",
        "RM": "oklch(87.95% 0.083 85.69)",
        "MARRIED": "oklch(76.52% 0.083 284.28)"
    }

    for state, companies in colorMapping.items():
        state_id = State.objects.get(full_state=state)
        for carrier, color in companies.items():
            # Get the company object
            try:
                carrier_id = Carrier.objects.get(carrier_name=carrier)
            except Carrier.DoesNotExist:
                print(f"Company {carrier} does not exist in the database.")
                carrier_id = None
                time.sleep(50)

            print(f"State: {state}, Carrier: {carrier}, Color: {color}")

            # decode the color
            color = ColorKey[color]

            # Get the color object
            discount_id = HouseHoldDiscountKey.objects.get(color=color)

            print(f"State ID: {state_id}, Carrier ID: {carrier_id}, Discount ID: {discount_id}")

            # Check if an entry with the same state and company already exists
            existing_entry = HouseHoldDiscount.objects.filter(state_id=state_id, carrier_id=carrier_id).first()
            if existing_entry is None:
                # Create a new HouseHoldDiscount object

                HouseHoldDiscount.objects.get_or_create(
                    state=state_id,
                    carrier=carrier_id,
                    discount=discount_id
                )
            else:
                print(f"Entry for state {state} and company {carrier} already exists.")


class Command(BaseCommand):
    help = 'Add color mapping to the HouseHoldDiscounts model'

    def handle(self, *args, **options):
        add_color_mapping_to_model()
        return 0
